"use client";

import { FadeIn } from "./fade-in";

const features = [
  {
    icon: "▓",
    title: "Terminal",
    desc: "Claude Code CLI runs front and center. Multi-tab support — run Claude and a shell side by side. Switch between Opus, Sonnet, and Haiku per tab.",
  },
  {
    icon: "⊞",
    title: "File Tree",
    desc: "Full project structure with real-time git status indicators. 50+ file type icons. See exactly what Claude is changing without switching to Finder.",
  },
  {
    icon: "◉",
    title: "Diff Viewer",
    desc: "Unified or split diffs with intra-line highlighting. Stage, unstage, or discard at the hunk level. Review every change Claude made before committing.",
  },
  {
    icon: "⑂",
    title: "Git Management",
    desc: "Branches, stash, merge conflicts, commit history — all through a clean interface. Stage, commit, and push code generated by Claude without leaving the app.",
  },
  {
    icon: "◎",
    title: "Browser Preview",
    desc: "Built-in browser pointed at your dev server. Auto-refreshes on file changes. 6 device presets from iPhone SE to Desktop with zoom from 25% to 150%.",
  },
  {
    icon: "✎",
    title: "Code Editor",
    desc: "Quick manual edits without needing AI. 23-language syntax highlighting, git gutter markers, and per-line blame. Change one line without opening VS Code.",
  },
  {
    icon: "⟡",
    title: "Token Tracking",
    desc: "Real-time token usage monitoring. Track cost per session and per prompt. Know exactly what you're spending daily and weekly — no surprises.",
  },
  {
    icon: "↻",
    title: "Conversation History",
    desc: "Every Claude session saved automatically. Revisit previous prompts and outputs at any time. Never lose context from a previous session.",
  },
];

function FeatureCard({
  icon,
  title,
  desc,
  delay,
}: {
  icon: string;
  title: string;
  desc: string;
  delay: number;
}) {
  return (
    <FadeIn delay={delay}>
      <div className="bg-surface border border-border rounded-[14px] p-7 transition-all duration-200 hover:border-amber/25 hover:-translate-y-0.5 group h-full">
        <div className="text-[28px] mb-3.5 text-amber opacity-70 group-hover:opacity-100 transition-opacity">
          {icon}
        </div>
        <h3 className="text-[16px] font-semibold text-white mb-2 font-mono">
          {title}
        </h3>
        <p className="text-sm text-muted leading-relaxed">{desc}</p>
      </div>
    </FadeIn>
  );
}

export function Features() {
  return (
    <section className="max-w-[1100px] mx-auto mb-24 px-6">
      <FadeIn>
        <div className="text-center mb-4">
          <h2 className="text-[32px] font-extrabold text-white font-mono tracking-tight">
            Everything around Claude Code CLI.
            <br />
            <span className="text-amber">In one 10MB app.</span>
          </h2>
        </div>
      </FadeIn>
      <FadeIn delay={0.05}>
        <p className="text-center text-muted text-[15px] max-w-[500px] mx-auto mb-12">
          8 integrated tools that replace the apps you keep alt-tabbing between.
          Claude stays the core — everything else supports it.
        </p>
      </FadeIn>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {features.map((f, i) => (
          <FeatureCard key={f.title} {...f} delay={i * 0.05} />
        ))}
      </div>
    </section>
  );
}
